name: Terraform

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '=2.90.0'
      - name: Check Terraform version
        run: terraform version
      - name: Terraform Init
        run: terraform init -upgrade
        env:
          ARM_PROVIDER_VERSION: "=3.6.0"
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Apply
        run: terraform apply --auto-approve
      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'BackendGrupo02'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './App.zip'
